# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/

# 1. 網站標題與網址
title: 'Mao-Chang Ku (古貿昌)'
baseURL: 'https://kumaochang.github.io/' # 上線前記得改回你的 GitHub Pages 網址

############################
## LANGUAGE & MENUS
############################

defaultContentLanguage: en
hasCJKLanguage: true # 開啟對中文的支援
defaultContentLanguageInSubdir: false
removePathAccents: true

# 2. 網站選單 (這裡設定網站上方的導覽列)
menu:
  main:
    - name: Home
      url: "#about"
      weight: 10
    - name: Publications
      url: "#featured"
      weight: 20
    - name: Teaching
      url: "#teaching"
      weight: 30
    - name: Projects
      url: "#projects"
      weight: 40
    - name: Contact
      url: "#contact"
      weight: 50

############################
## PAGE OPTIONS
############################

cascade:
  - _target:
      path: /slides/**
      kind: page
    outputs: [HTML, present]

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep

# 3. 額外參數 (確保你的名字會正確顯示)
params:
  hugoblox:
    branding:
      name: "Mao-Chang Ku"
  description: "Ph.D. Student in Linguistics at NTU, specializing in Computational Linguistics."
